package pl.industrum.gasanalyzer.model;

// default package
// Generated 2013-05-07 14:42:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationUser generated by hbm2java
 */
public class ApplicationUser implements java.io.Serializable
{

	private int id;
	private Function function;
	private Degree degree;
	private String name;
	private String surname;
	private Set surveys = new HashSet( 0 );

	public ApplicationUser()
	{
	}

	public ApplicationUser( int id, Function function, Degree degree,
			String name, String surname )
	{
		this.id = id;
		this.function = function;
		this.degree = degree;
		this.name = name;
		this.surname = surname;
	}

	public ApplicationUser( int id, Function function, Degree degree,
			String name, String surname, Set surveys )
	{
		this.id = id;
		this.function = function;
		this.degree = degree;
		this.name = name;
		this.surname = surname;
		this.surveys = surveys;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId( int id )
	{
		this.id = id;
	}

	public Function getFunction()
	{
		return this.function;
	}

	public void setFunction( Function function )
	{
		this.function = function;
	}

	public Degree getDegree()
	{
		return this.degree;
	}

	public void setDegree( Degree degree )
	{
		this.degree = degree;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName( String name )
	{
		this.name = name;
	}

	public String getSurname()
	{
		return this.surname;
	}

	public void setSurname( String surname )
	{
		this.surname = surname;
	}

	public Set getSurveys()
	{
		return this.surveys;
	}

	public void setSurveys( Set surveys )
	{
		this.surveys = surveys;
	}

}
