package pl.industrum.gasanalyzer.model;

// default package
// Generated 2013-05-07 14:42:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * DeviceType generated by hbm2java
 */
@SuppressWarnings( { "rawtypes", "serial" } )
public class DeviceType implements java.io.Serializable
{

	private int id;
	private String type;
	private byte[] document;
	private Set devices = new HashSet( 0 );

	public DeviceType()
	{
	}

	public DeviceType( int id, String type )
	{
		this.id = id;
		this.type = type;
	}

	public DeviceType( int id, String type, byte[] document, Set devices )
	{
		this.id = id;
		this.type = type;
		this.document = document;
		this.devices = devices;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId( int id )
	{
		this.id = id;
	}

	public String getType()
	{
		return this.type;
	}

	public void setType( String type )
	{
		this.type = type;
	}

	public byte[] getDocument()
	{
		return this.document;
	}

	public void setDocument( byte[] document )
	{
		this.document = document;
	}

	public Set getDevices()
	{
		return this.devices;
	}

	public void setDevices( Set devices )
	{
		this.devices = devices;
	}

}
