package pl.industrum.gasanalyzer.model;

// default package
// Generated 2013-05-07 14:42:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Function generated by hbm2java
 */
@SuppressWarnings( { "rawtypes", "serial" } )
public class Function implements java.io.Serializable
{

	private int id;
	private String name;
	private Set applicationUsers = new HashSet( 0 );

	public Function()
	{
	}

	public Function( int id, String name )
	{
		this.id = id;
		this.name = name;
	}

	public Function( int id, String name, Set applicationUsers )
	{
		this.id = id;
		this.name = name;
		this.applicationUsers = applicationUsers;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId( int id )
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName( String name )
	{
		this.name = name;
	}

	public Set getApplicationUsers()
	{
		return this.applicationUsers;
	}

	public void setApplicationUsers( Set applicationUsers )
	{
		this.applicationUsers = applicationUsers;
	}

}
