package pl.industrum.gasanalyzer.model;

// default package
// Generated 2013-05-07 14:42:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * MeasurementDimension generated by hbm2java
 */
@SuppressWarnings( { "rawtypes", "serial" } )
public class MeasurementDimension implements java.io.Serializable
{

	private int id;
	private String name;
	private Set measurements = new HashSet( 0 );

	public MeasurementDimension()
	{
	}

	public MeasurementDimension( int id, String name )
	{
		this.id = id;
		this.name = name;
	}

	public MeasurementDimension( int id, String name, Set measurements )
	{
		this.id = id;
		this.name = name;
		this.measurements = measurements;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId( int id )
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName( String name )
	{
		this.name = name;
	}

	public Set getMeasurements()
	{
		return this.measurements;
	}

	public void setMeasurements( Set measurements )
	{
		this.measurements = measurements;
	}

}
