package pl.industrum.gasanalyzer.model;

// default package
// Generated 2013-05-07 14:42:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Place generated by hbm2java
 */
@SuppressWarnings( { "rawtypes", "serial" } )
public class Place implements java.io.Serializable
{

	private int id;
	private String name;
	private String city;
	private String postCode;
	private String address;
	private Set objects = new HashSet( 0 );

	public Place()
	{
	}

	public Place( int id )
	{
		this.id = id;
	}

	public Place( int id, String name, String city, String postCode,
			String address, Set objects )
	{
		this.id = id;
		this.name = name;
		this.city = city;
		this.postCode = postCode;
		this.address = address;
		this.objects = objects;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId( int id )
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName( String name )
	{
		this.name = name;
	}

	public String getCity()
	{
		return this.city;
	}

	public void setCity( String city )
	{
		this.city = city;
	}

	public String getPostCode()
	{
		return this.postCode;
	}

	public void setPostCode( String postCode )
	{
		this.postCode = postCode;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress( String address )
	{
		this.address = address;
	}

	public Set getObjects()
	{
		return this.objects;
	}

	public void setObjects( Set objects )
	{
		this.objects = objects;
	}

	@Override
	public String toString()
	{
		return getName() + " - " + getAddress() + ", " + getPostCode() + " " + getCity();
	}
	
	@Override
	public boolean equals( Object obj )
	{
		Place place = ( Place )obj;
		if ( id == place.id )
		{
			return true;
		}
		
		return false;
	}
}
